### PR TITLE
Code review fixes

### PR DESCRIPTION
**Pull request by paulianttila**

### CODE REVIEW

**Comment by lucacalcaterra** [comment]
No too much  experience with git and others authors.. Before this there is another Pr. If I accept all PR what happens ?

**Comment by paulianttila** [comment]
It seems that both pr’s have changes to same files, so merge conflicts might occur.

**Comment by thewiep** [comment]
If you merge this PR I'll rebase my PR, make required changes to my commits and update the PR.
That way it should be a clean merge.

**Comment by lucacalcaterra** [comment]
Ok don't know i've time to spent on it this week end

Il giorno sab 21 set 2019 alle ore 22:24 Wietse van Buitenen <
notifications@github.com> ha scritto:

**Comment by paulianttila** [comment]
@lucacalcaterra, when do you think you could find time to merge this PR, so that @thewiep can continue his work?

**Comment by lucacalcaterra** [comment]
Asap. I'm finishing a work.  This w.e. or monday  probably..

Il Sab 5 Ott 2019, 10:54 pali <notifications@github.com> ha scritto:

**Pull request merged**
